### ISSUE TITLE
FormatException: input string was not in a correct format

### ISSUE THREAD

**Issue by manification10** [chenjd/Unity-ARFoundation-HandDetection#1]
<img width="1115" alt="Screen Shot 2019-09-29 at 11 44 45 AM" src="https://user-images.githubusercontent.com/5540743/65834962-a01db880-e2ae-11e9-8ed1-4445023771bd.png">

**Comment by chenjd** [comment]
Hi @manification10 . Sorry for the late reply. I think you should build it to iOS.
