### ISSUE TITLE
Package manager problems

### ISSUE THREAD

**Issue by Acimaz** [chenjd/Unity-ARFoundation-HandDetection#3]
Pushing the manifest.json could help prevent lots of problems with wrong package versions.

**Comment by chenjd** [comment]
Hi @Acimaz . The manifest.json file under the Packages folder has been pushed.  Since you also mentioned the `version problem`, so I use some local packages. You can find them at the json file.

    "com.unity.xr.arfoundation": "file:../ARPackages/com.unity.xr.arfoundation",
    "com.unity.xr.arkit": "file:../ARPackages/com.unity.xr.arkit"
